import { OFFICIAL_V133_SHA256, inspectHtfw, makePlan, transferFirmware } from './pocket-master-core.mjs';
import { requestSysexAccess, listPairs, describePair, openPair, enterBootloader, waitForBootloaderPair, waitForNormalPair } from './pocket-master-webmidi.mjs';

const CUSTOM_V07_SHA256='4d2d50fcb0273692db0d17babf18b785c9c10b11305406ce1790ccb2fe26230b';
const FAILED_V08_SHA256='2678e13c98145a2b33747801c462981263ff6c215d61a6fc0f9243f870b63b94';
const $=s=>document.querySelector(s);
const ui={connect:$('#connectBtn'),file:$('#firmwareFile'),device:$('#deviceSelect'),inspect:$('#inspectBox'),boot:$('#bootBtn'),flash:$('#flashBtn'),progress:$('#progress'),progressText:$('#progressText'),state:$('#state'),log:$('#log'),agree:$('#agree'),cancel:$('#cancelBtn'),browser:$('#browserStatus')};
let access=null,firmware=null,info=null,plan=null,aborter=null,busy=false;
const log=s=>{const ts=new Date().toLocaleTimeString();ui.log.textContent+=`[${ts}] ${s}\n`;ui.log.scrollTop=ui.log.scrollHeight};
const state=s=>{ui.state.textContent=s;log(`STATE: ${s}`)};
function kind(){if(!info)return null;if(info.sha256===OFFICIAL_V133_SHA256)return'stock';if(info.sha256===CUSTOM_V07_SHA256)return'v07';return null}
function selectedPair(){return[...ui.device.options].find(o=>o.value===ui.device.value)?._pair||null}
const canBoot=()=>!!(access&&selectedPair());
const canFlash=()=>!!(canBoot()&&firmware&&plan&&kind()&&ui.agree.checked);
function updateLabel(){ui.flash.textContent=kind()==='stock'?'3B · FLASH OFFICIAL V1.3.3':kind()==='v07'?'3B · FLASH POCKET FX v0.7':'3B · FLASH BLOCKED'}
function setBusy(v){busy=v;ui.connect.disabled=v;ui.file.disabled=v;ui.device.disabled=v;ui.boot.disabled=v||!canBoot();ui.flash.disabled=v||!canFlash();ui.cancel.hidden=!v;updateLabel()}
function refresh(){const prior=ui.device.value;ui.device.innerHTML='';if(!access){ui.device.innerHTML='<option value="">Connect MIDI first</option>';setBusy(busy);return}const pairs=listPairs(access);for(const p of pairs){const o=document.createElement('option');o.value=p.input.id;o.textContent=describePair(p);o._pair=p;ui.device.appendChild(o)}if(prior&&[...ui.device.options].some(o=>o.value===prior))ui.device.value=prior;if(!pairs.length)ui.device.innerHTML='<option value="">No MIDI input/output pair</option>';setBusy(busy)}
async function loadFile(file){firmware=new Uint8Array(await file.arrayBuffer());info=await inspectHtfw(firmware);plan=null;let r=`File: ${file.name}\nSize: ${info.size.toLocaleString()} bytes\nMagic: ${info.isHtfw?'HTFW ✓':'NO'}\nVersion: ${info.versionTag||'?'}\nSHA-256: ${info.sha256}\nFletcher16: 0x${(info.fletcher16??0).toString(16).padStart(4,'0').toUpperCase()}\nRegions: ${info.regions.length}\n`;for(const x of info.regions)r+=`  ${x.id}: len=0x${x.length.toString(16).toUpperCase()} CRC16=${x.crcValid?'OK':'FAIL'}\n`;if(info.isHtfw&&info.allRegionCrcsValid){plan=await makePlan(firmware);r+=`Data packets: ${plan.totalDataPackets.toLocaleString()}\n`;if(info.sha256===FAILED_V08_SHA256)r+='Safety lock: TTG FX v0.8 DISABLED — hardware test showed silent DST/AMP slots.\n';else r+=kind()==='stock'?'Safety lock: OFFICIAL V1.3.3 ✓\n':kind()==='v07'?'Safety lock: POCKET FX v0.7 ✓ — hardware verified baseline.\n':'Safety lock: UNKNOWN/CUSTOM — WRITE BLOCKED.\n'}else r+='WRITE BLOCKED: invalid HTFW/CRC.\n';ui.inspect.textContent=r;setBusy(busy)}
ui.connect.onclick=async()=>{try{access=await requestSysexAccess();access.onstatechange=refresh;log('MIDI + SysEx permission granted.');refresh()}catch(e){log(`ERROR: ${e.message}`);state('MIDI PERMISSION ERROR')}};
ui.file.onchange=async()=>{const f=ui.file.files[0];if(f)try{await loadFile(f)}catch(e){log(`ERROR: ${e.message}`)}};
ui.agree.onchange=()=>setBusy(busy);ui.device.onchange=()=>setBusy(busy);ui.cancel.onclick=()=>aborter?.abort();
ui.boot.onclick=async()=>{if(!canBoot())return;setBusy(true);aborter=new AbortController();try{state('ENTER BOOTLOADER · NO FLASH');const old=await enterBootloader(access,plan,selectedPair(),log);state('WAIT BOOTLOADER MIDI');const boot=await waitForBootloaderPair(access,old,12000,log);const link=await openPair(boot);link.close();state('BOOTLOADER RECONNECT PASSED');log('No flash data was written. Power-cycle to return to normal mode.')}catch(e){state('TEST FAILED');log(`ERROR: ${e.message}`)}finally{aborter=null;setBusy(false);refresh()}};
ui.flash.onclick=async()=>{if(!canFlash())return;const k=kind();setBusy(true);aborter=new AbortController();ui.progress.value=0;ui.progressText.textContent='0%';let link=null;try{if(!k)throw new Error('Write lock accepts only official V1.3.3 or the hardware-verified Pocket FX v0.7 baseline.');log(`Selected image: ${k==='stock'?'OFFICIAL V1.3.3':'POCKET FX v0.7'}.`);state('ENTER BOOTLOADER');const old=await enterBootloader(access,plan,selectedPair(),log);state('WAIT BOOTLOADER MIDI');const boot=await waitForBootloaderPair(access,old,12000,log);link=await openPair(boot);log(`Bootloader opened: ${describePair(boot)}`);const result=await transferFirmware(firmware,link,{state,progress(done,total){const pct=Math.floor(done*100/total);ui.progress.value=pct;ui.progressText.textContent=`${pct}% · ${done.toLocaleString()} / ${total.toLocaleString()}`},log},aborter.signal);link.close();link=null;log(`Transfer finalized. sends=${result.packetsSent.toLocaleString()} retries=${result.retries}`);state('WAIT NORMAL REBOOT');const back=await waitForNormalPair(access,15000);if(back){state(k==='stock'?'FLASH COMPLETE · STOCK':'FLASH COMPLETE · v0.7');log(`Pocket Master returned: ${describePair(back)}`)}else{state('TRANSFER COMPLETE · POWER CYCLE MAY BE NEEDED');log('Normal MIDI port was not observed before timeout. Power-cycle once.')}}catch(e){state(e.name==='AbortError'?'CANCELLED':'FLASH ERROR');log(`ERROR: ${e.message}`)}finally{try{link?.close()}catch(_){}aborter=null;setBusy(false);refresh()}};
window.addEventListener('beforeunload',e=>{if(busy){e.preventDefault();e.returnValue=''}});
const ok=!!navigator.requestMIDIAccess&&window.isSecureContext;ui.browser.textContent=ok?'WebMIDI/SysEx: browser candidate OK':`WebMIDI/SysEx unavailable · secure=${window.isSecureContext}`;ui.browser.className=ok?'ok':'bad';refresh();setBusy(false);
